# We don't need this again to expose our mongodb to the outside world
# All the configuration should be done in the values.yaml file
{{- if .Values.mongodb.ingress.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" $.Release.Name "mongo-external"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: oneuptime
    app.kubernetes.io/managed-by: Helm
data:
  27017: {{ printf "%s/$s" $.Release.Namespace "fi-mongodb:27017" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Release.Name "mongo-ingress"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: oneuptime
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - name: proxied-tcp-27017
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb
{{- end }}
---