########-INIT-SCRIPT-##########
apiVersion: batch/v1
kind: Job
metadata:
    name: {{ printf "%s-%s" .Release.Name "init-script"  }}
    namespace: {{ .Release.Namespace }}
    labels:
      app.kubernetes.io/part-of: oneuptime
      app.kubernetes.io/managed-by: Helm
spec:
    template:
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository "init-script" .Values.image.tag }}
                  name: {{ printf "%s-%s" .Release.Name "init-script"  }}
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  env:
                      - name: SERVER_URL
                        value: {{ template "oneuptime.serverUrl" $ }}
                      - name: MONGO_URL
                        value:  {{ template "oneuptime.mongodbConnectionString" . }}
                      - name: NODE_ENV
                        value: 'production'
                      - name: ENCRYPTION_KEY
                        valueFrom:
                          configMapKeyRef:
                            name: {{ printf "%s-%s" .Release.Name "configmap"  }}
                            key: encryptionkey
                      - name: CLUSTER_KEY
                        valueFrom:
                          configMapKeyRef:
                            name: {{ printf "%s-%s" .Release.Name "configmap"  }}
                            key: clusterkey
                      {{- if .Values.saas.isSaasService }}
                      - name: STRIPE_PUBLIC_KEY
                        value: {{ .Values.saas.stripe.publicKey }}
                      - name: STRIPE_PRIVATE_KEY
                        value: {{ .Values.saas.stripe.privateKey }}
                      {{- end }}
            restartPolicy: Never
---
####################################