############----INGRESS---#####################################

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ printf "%s-%s" .Release.Name "ingress"  }}
spec:
  rules:
    - http:
        paths:
          - path: /accounts
            backend:
              serviceName: {{ printf "%s-%s" .Release.Name "accounts"  }}
              servicePort: 80
          - path: /dashboard
            backend:
              serviceName: {{ printf "%s-%s" .Release.Name "dashboard"  }}
              servicePort: 80
          - path: /admin
            backend:
              serviceName: {{ printf "%s-%s" .Release.Name "admin-dash"  }}
              servicePort: 80
          - path: /api
            backend:
              serviceName: {{ printf "%s-%s" .Release.Name "backend"  }}
              servicePort: 80
          - path: /statuspage
            backend:
              serviceName: {{ printf "%s-%s" .Release.Name "status-page"  }}
              servicePort: 80
          {{- if .Values.saas.isSaasService }}
          - path: /slack
            backend:
              serviceName: {{ printf "%s-%s" .Release.Name "slack"  }}
              servicePort: 80
          - path: /
            backend:
              serviceName: {{ printf "%s-%s" .Release.Name "home"  }}
              servicePort: 80
          - path: /docs
            backend:
              serviceName: {{ printf "%s-%s" .Release.Name "api-docs"  }}
              servicePort: 80
          {{- end }}   
---
##################################