#########
#Since Kubernetes jobs are immitable (you cannot update it with a new image).
# To update these jobs, CI deletes the old jobs and recreates them using this file.
#########

#########
#UPDATE: Any update to this file should also be accompanied with ../production.yaml
#########

########-INIT-SCRIPT-##########
apiVersion: batch/v1
kind: Job
metadata:
    name: fi-init-script
spec:
    template:
        spec:
            containers:
                - name: fi-init-script
                  image: fyipeproject/init-script:latest
                  imagePullPolicy: Always
                  env:
                      - name: NODE_ENV
                        value: 'production'
                      - name: MONGO_URL
                        value: 'mongodb://8aKfamHvEqOjFVTZNNXN:5ojKi7gKK0PcgQmNxSpC@fi-mongodb.default.svc.cluster.local:27017/fyipedb?replicaSet=rs0'
            restartPolicy: Never
---
###########################
