############-----HOME----#############################
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ printf "%s-%s" $.Release.Name "home"  }}
    namespace: {{ $.Release.Namespace }}
    labels:
        app: {{ printf "%s-%s" $.Release.Name "home"  }}
        app.kubernetes.io/part-of: oneuptime
        app.kubernetes.io/managed-by: Helm
spec:
    selector:
        matchLabels:
            app: {{ printf "%s-%s" $.Release.Name "home"  }}
    replicas: {{ $.Values.replicaCount }}
    template:
        metadata:
            labels:
                app: {{ printf "%s-%s" $.Release.Name "home"  }}
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository "home" .Values.image.tag }}
                  name: {{ printf "%s-%s" $.Release.Name "home"  }}
                  imagePullPolicy: {{ $.Values.image.pullPolicy }}
                  resources:
                    requests:
                      cpu: 250m
                    limits:
                      cpu: 500m  
                  env:
                      {{- include "oneuptime.env.common" . | nindent 22 }}
                      {{- include "oneuptime.env.commonUi" . | nindent 22 }}
                      - name: NODE_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.nodeName
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_IP
                        valueFrom:
                          fieldRef:
                            fieldPath: status.podIP
                      - name: POD_SERVICE_ACCOUNT
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.serviceAccountName
                  ports:
                      - containerPort: {{ $.Values.port.home }}
                        hostPort: {{ $.Values.port.home }}
                        name: {{ printf "%s-%s" $.Release.Name "home"  }}
            restartPolicy: {{ $.Values.image.restartPolicy }}

---
# OneUptime home Service
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ printf "%s-%s" $.Release.Name "home"  }}
        app.kubernetes.io/part-of: oneuptime
        app.kubernetes.io/managed-by: Helm
    name: {{ printf "%s-%s" $.Release.Name "home"  }}
    namespace: {{ $.Release.Namespace }}
spec:
    ports:
        - port: {{ $.Values.port.home }}
          targetPort: {{ $.Values.port.home }}
    selector:
        app: {{ printf "%s-%s" $.Release.Name "home"  }}
    type: ClusterIP
---
###########################################


{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodautoscaling
metadata:
  name: {{ printf "%s-%s" $.Release.Name "home"  }}
  namespace: {{ $.Release.Namespace }}
spec:
  maxReplicas: {{ $.Values.autoscaling.maxReplicas }}
  minReplicas: {{ $.Values.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" $.Release.Name "home"  }}
  targetCPUUtilizationPercentage: {{ $.Values.autoscaling.targetCPUUtilizationPercentage }}
  targetMemoryUtilizationPercentage: {{ $.Values.autoscaling.targetMemoryUtilizationPercentage }}
---
{{- end }}