apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $.Release.Name "secrets"  }}
type: Opaque
data:
  oneuptime-secret: {{ randAlphaNum 32 | b64enc | quote }}
  encryption-secret: {{ randAlphaNum 32 | b64enc | quote }}