# OneUptime workflow Service
{{- $workflowDeploymentArgs :=dict "ServiceName" "workflow" "Port" $.Values.port.workflow "Release" $.Release "Values" $.Values -}}
{{- include "oneuptime.deployment" $workflowDeploymentArgs }}
---

# OneUptime workflow Service
{{- $workflowEnv := dict "PORT"  $.Values.port.workflow -}}
{{- $workflowServiceArgs := dict "IsServer" "true" "ServiceName" "workflow" "Port" $.Values.port.workflow "Release" $.Release "Values" $.Values "Env" $workflowEnv -}}
{{- include "oneuptime.service" $workflowServiceArgs }}
---

# OneUptime workflow Service
{{- $workflowAutoScalerArgs := dict "ServiceName" "workflow" "Release" $.Release "Values" $.Values -}}
{{- include "oneuptime.autoscaler" $workflowAutoScalerArgs }}
---