# IMPORTANT:
#
# This CI/CD will run on an Ubuntu VM. After this script runs, the VM will retain the state.
# It's your responsibility to clean the VM up in the cleanup stage after job finishes executing.
# This script runs on Microk8s. Since our deployments are on Kubernetes, our aim is to create EXACT same replica for test, staging and production.

# Define stages
stages:
  - BuildAndTest
  - Deploy
  - RollbackIfDeploymentFail
  - Tests
  - RollbackIfTestsFail

include:
  # GLOBAL JOBS
  - '/ci/spec/global/lint.yaml'
  - '/ci/spec/global/rollback.yaml'

  # ACCOUNTS
  - '/ci/spec/accounts/audit.yaml'
  - '/ci/spec/accounts/deploy.yaml'
  - '/ci/spec/accounts/rollback.yaml'
  - '/ci/spec/accounts/lighthouse.yaml'

  # ADMIN DASHBOARD
  - '/ci/spec/AdminDashboard/audit.yaml'
  - '/ci/spec/AdminDashboard/deploy.yaml'
  - '/ci/spec/AdminDashboard/rollback.yaml'

  # ApiDocs DASHBOARD
  - '/ci/spec/ApiDocs/audit.yaml'
  - '/ci/spec/ApiDocs/deploy.yaml'
  - '/ci/spec/ApiDocs/rollback.yaml'

  # BACKEND
  - '/ci/spec/backend/audit.yaml'
  - '/ci/spec/backend/build-n-test.yaml'
  - '/ci/spec/backend/deploy.yaml'
  - '/ci/spec/backend/rollback.yaml'

  # DASHBOARD
  - '/ci/spec/dashboard/audit.yaml'
  - '/ci/spec/dashboard/deploy.yaml'
  - '/ci/spec/dashboard/rollback.yaml'

  # HelmChart
  - '/ci/spec/HelmChart/audit.yaml'
  - '/ci/spec/HelmChart/build-n-test.yaml'
  - '/ci/spec/HelmChart/deploy.yaml'
  - '/ci/spec/HelmChart/rollback.yaml'

  # HOME
  - '/ci/spec/home/audit.yaml'
  - '/ci/spec/home/deploy.yaml'
  - '/ci/spec/home/rollback.yaml'
  - '/ci/spec/home/lighthouse.yaml'

  # HttpTestServer
  - '/ci/spec/HttpTestServer/audit.yaml'
  - '/ci/spec/HttpTestServer/deploy.yaml'
  - '/ci/spec/HttpTestServer/rollback.yaml'

  # InitScript
  - '/ci/spec/InitScript/audit.yaml'
  - '/ci/spec/InitScript/deploy.yaml'

  # LIGHTHOUSE RUNNER
  - '/ci/spec/LighthouseRunner/audit.yaml'
  - '/ci/spec/LighthouseRunner/deploy.yaml'

  # LICENSING
  - '/ci/spec/licensing/audit.yaml'
  - '/ci/spec/licensing/build-n-test.yaml'
  - '/ci/spec/licensing/deploy.yaml'
  - '/ci/spec/licensing/rollback.yaml'

  # PROBE
  - '/ci/spec/probe/audit.yaml'
  - '/ci/spec/probe/deploy.yaml'
  - '/ci/spec/probe/rollback.yaml'

  # StatusPage
  - '/ci/spec/StatusPage/audit.yaml'
  - '/ci/spec/StatusPage/deploy.yaml'
  - '/ci/spec/StatusPage/rollback.yaml'

  # ZAPIER
  - '/ci/spec/zapier/audit.yaml'
  - '/ci/spec/zapier/build-n-test.yaml'

  # E2E
  - '/ci/spec/e2e/docker-compose-enterprise-test.yaml'
  - '/ci/spec/e2e/docker-compose-test.yaml'
  - '/ci/spec/e2e/kubernetes-enterprise-test.yaml'
  - '/ci/spec/e2e/kubernetes-test.yaml'

  # SMOKE TEST
  - '/ci/spec/tests/staging.yaml'
  - '/ci/spec/tests/production.yaml'

  # JavaScriptSDK
  - '/ci/spec/JavaScriptSDK/audit.yaml'
  - '/ci/spec/JavaScriptSDK/build-n-test.yaml'
  - '/ci/spec/JavaScriptSDK/deploy.yaml'

  # PhpSDK
  - '/ci/spec/PhpSDK/audit.yaml'
  - '/ci/spec/PhpSDK/build-n-test.yaml'
  - '/ci/spec/PhpSDK/deploy.yaml'

  # JavaSDK
  - '/ci/spec/JavaSDK/audit.yaml'
  - '/ci/spec/JavaSDK/build-n-test.yaml'
  - '/ci/spec/JavaSDK/deploy.yaml'

  # PythonSDK
  - '/ci/spec/PythonSDK/audit.yaml'
  - '/ci/spec/PythonSDK/build-n-test.yaml'
  - '/ci/spec/PythonSDK/deploy.yaml'

  # RUBY-SDK
  - '/ci/spec/ruby-sdk/audit.yaml'
  - '/ci/spec/ruby-sdk/build-n-test.yaml'
  - '/ci/spec/ruby-sdk/deploy.yaml'

  # HARAKA
  - '/ci/spec/haraka/deploy.yaml'

  # ONEUPTIME-LE-STORE
  - '/ci/spec/oneuptime-le-store/deploy.yaml'

  # ONEUPTIME-ACME-HTTP-01
  - '/ci/spec/oneuptime-acme-http-01/deploy.yaml'

  # ONEUPTIME-GL-MANAGER
  - '/ci/spec/oneuptime-gl-manager/deploy.yaml'

  # Application Scanner
  - '/ci/spec/ApplicationScanner/deploy.yaml'

  #  Script Runner
  - '/ci/spec/ScriptRunner/audit.yaml'
  - '/ci/spec/ScriptRunner/deploy.yaml'

  #  Container Scanner
  - '/ci/spec/ContainerScanner/deploy.yaml'

  # realtime
  - '/ci/spec/realtime/audit.yaml'
  - '/ci/spec/realtime/deploy.yaml'
  - '/ci/spec/realtime/rollback.yaml'

  # data-ingestor
  - '/ci/spec/data-ingestor/audit.yaml'
  - '/ci/spec/data-ingestor/deploy.yaml'
  - '/ci/spec/data-ingestor/rollback.yaml'

  # ProbeAPI
  - '/ci/spec/ProbeAPI/audit.yaml'
  - '/ci/spec/ProbeAPI/deploy.yaml'
  - '/ci/spec/ProbeAPI/rollback.yaml'

  # # GoSDK
  # - '/ci/spec/GoSDK/audit.yaml'
  # - '/ci/spec/GoSDK/build-n-test.yaml'
  # - '/ci/spec/GoSDK/deploy.yaml'
