# IMPORTANT:
#
# This CI/CD will run on an Ubuntu VM. After this script runs, the VM will retain the state.
# It's your responsibility to clean the VM up in the cleanup stage after job finishes executing.
# This script runs on Microk8s. Since our deployments are on Kubernetes, our aim is to create EXACT same replica for test, staging and production.

# Define stages
stages:
  - BuildAndTest
  - E2E
  - Deploy
  - RollbackIfDeploymentFail
  - SmokeTest
  - RollbackIfSmokeTestFail
  - CleanUp

include:
  # GLOBAL JOBS
  - '/ci/spec/global/lint.yaml'
  - '/ci/spec/global/cleanup.yaml'
  - '/ci/spec/global/rollback-staging.yaml'
  - '/ci/spec/global/rollback-production.yaml'

  # ACCOUNTS
  - '/ci/spec/accounts/audit.yaml'
  - '/ci/spec/accounts/build-n-test.yaml'
  - '/ci/spec/accounts/build-n-test-entreprise.yaml'
  - '/ci/spec/accounts/deploy-staging.yaml'
  - '/ci/spec/accounts/deploy-production.yaml'
  - '/ci/spec/accounts/staging-rollback.yaml'
  - '/ci/spec/accounts/production-rollback.yaml'
  - '/ci/spec/accounts/desktop-lighthouse.yaml'
  - '/ci/spec/accounts/mobile-lighthouse.yaml'

  # ADMIN DASHBOARD
  - '/ci/spec/admin-dashboard/audit.yaml'
  - '/ci/spec/admin-dashboard/build-n-test.yaml'
  - '/ci/spec/admin-dashboard/build-n-test-entreprise.yaml'
  - '/ci/spec/admin-dashboard/deploy-staging.yaml'
  - '/ci/spec/admin-dashboard/deploy-production.yaml'
  - '/ci/spec/admin-dashboard/staging-rollback.yaml'
  - '/ci/spec/admin-dashboard/production-rollback.yaml'

  # API-DOCS DASHBOARD
  - '/ci/spec/api-docs/audit.yaml'
  - '/ci/spec/api-docs/build-n-test.yaml'
  - '/ci/spec/api-docs/deploy-staging.yaml'
  - '/ci/spec/api-docs/deploy-production.yaml'
  - '/ci/spec/api-docs/staging-rollback.yaml'
  - '/ci/spec/api-docs/production-rollback.yaml'

  # BACKEND
  - '/ci/spec/backend/audit.yaml'
  - '/ci/spec/backend/build-n-test.yaml'
  - '/ci/spec/backend/build-n-test-entreprise.yaml'
  - '/ci/spec/backend/deploy-staging.yaml'
  - '/ci/spec/backend/deploy-production.yaml'
  - '/ci/spec/backend/staging-rollback.yaml'
  - '/ci/spec/backend/production-rollback.yaml'

  # DASHBOARD
  - '/ci/spec/dashboard/audit.yaml'
  - '/ci/spec/dashboard/build-n-test.yaml'
  - '/ci/spec/dashboard/build-n-test-entreprise.yaml'
  - '/ci/spec/dashboard/deploy-staging.yaml'
  - '/ci/spec/dashboard/deploy-production.yaml'
  - '/ci/spec/dashboard/staging-rollback.yaml'
  - '/ci/spec/dashboard/production-rollback.yaml'

  # HELM-CHART
  - '/ci/spec/helm-chart/audit.yaml'
  - '/ci/spec/helm-chart/build-n-test.yaml'
  - '/ci/spec/helm-chart/deploy-staging.yaml'
  - '/ci/spec/helm-chart/deploy-production.yaml'
  - '/ci/spec/helm-chart/staging-rollback.yaml'
  - '/ci/spec/helm-chart/production-rollback.yaml'

  # HOME
  - '/ci/spec/home/audit.yaml'
  - '/ci/spec/home/build-n-test.yaml'
  - '/ci/spec/home/deploy-staging.yaml'
  - '/ci/spec/home/deploy-production.yaml'
  - '/ci/spec/home/staging-rollback.yaml'
  - '/ci/spec/home/production-rollback.yaml'
  - '/ci/spec/home/desktop-lighthouse.yaml'
  - '/ci/spec/home/mobile-lighthouse.yaml'

  # HTTP-TEST-SERVER
  - '/ci/spec/http-test-server/audit.yaml'
  - '/ci/spec/http-test-server/build-n-test.yaml'
  - '/ci/spec/http-test-server/deploy-staging.yaml'
  - '/ci/spec/http-test-server/deploy-production.yaml'
  - '/ci/spec/http-test-server/staging-rollback.yaml'
  - '/ci/spec/http-test-server/production-rollback.yaml'

  # INIT-SCRIPT
  - '/ci/spec/init-script/audit.yaml'
  - '/ci/spec/init-script/build-n-test.yaml'
  - '/ci/spec/init-script/deploy-staging.yaml'
  - '/ci/spec/init-script/deploy-production.yaml'

  # LICENSING
  - '/ci/spec/licensing/audit.yaml'
  - '/ci/spec/licensing/build-n-test.yaml'
  - '/ci/spec/licensing/deploy-staging.yaml'
  - '/ci/spec/licensing/deploy-production.yaml'
  - '/ci/spec/licensing/staging-rollback.yaml'
  - '/ci/spec/licensing/production-rollback.yaml'

  # PROBE
  - '/ci/spec/probe/audit.yaml'
  - '/ci/spec/probe/build-n-test.yaml'
  - '/ci/spec/probe/deploy-staging.yaml'
  - '/ci/spec/probe/deploy-production.yaml'
  - '/ci/spec/probe/staging-rollback.yaml'
  - '/ci/spec/probe/production-rollback.yaml'

  # SERVER-MONITOR
  - '/ci/spec/server-monitor/audit.yaml'
  - '/ci/spec/server-monitor/build-n-test.yaml'
  - '/ci/spec/server-monitor/deploy-staging.yaml'
  - '/ci/spec/server-monitor/deploy-production.yaml'
  - '/ci/spec/server-monitor/staging-rollback.yaml'
  - '/ci/spec/server-monitor/production-rollback.yaml'

  # SLACK
  - '/ci/spec/slack/audit.yaml'
  - '/ci/spec/slack/build-n-test.yaml'
  - '/ci/spec/slack/deploy-staging.yaml'
  - '/ci/spec/slack/deploy-production.yaml'
  - '/ci/spec/slack/staging-rollback.yaml'
  - '/ci/spec/slack/production-rollback.yaml'

  # STATUS-PAGE
  - '/ci/spec/status-page/audit.yaml'
  - '/ci/spec/status-page/build-n-test.yaml'
  - '/ci/spec/status-page/deploy-staging.yaml'
  - '/ci/spec/status-page/deploy-production.yaml'
  - '/ci/spec/status-page/staging-rollback.yaml'
  - '/ci/spec/status-page/production-rollback.yaml'

  # ZAPIER
  - '/ci/spec/zapier/audit.yaml'
  - '/ci/spec/zapier/build-n-test.yaml'

  # E2E
  - '/ci/spec/e2e/docker-compose-entreprise-test.yaml'
  - '/ci/spec/e2e/docker-compose-test.yaml'
  - '/ci/spec/e2e/kubernetes-enterprise-test.yaml'
  - '/ci/spec/e2e/kubernetes-test.yaml'

  #SMOKE TEST
  - '/ci/spec/smoke-tests/staging.yaml'
  - '/ci/spec/smoke-tests/production.yaml'