version: '3.7'

services:
    
    probe:   
        extends:
            file: ./docker-compose.base.yml
            service: probe
        build:
            network: host
            context: .
            dockerfile: ./Probe/Dockerfile
