version: '3.7'
services:
    mongo:
        image: mongo:4.2.3
        ports:
            - '27017:27017'
        volumes:
            - mongodata:/data/db

    redis:
        image: redis:5.0.7
        ports:
            - '6379:6379'
        command: redis-server

    backend:
        ports:
            - '3002:3002'
        build: ./backend
        env_file:
            - ./backend/.env
        environment:
            - MONGO_URL=mongodb://mongo:27017/fyipedb
            - REDIS_HOST=redis
            - IS_SAAS_SERVICE=true
        depends_on:
            - mongo
            - redis
            # - haraka

    accounts:
        ports:
            - '3003:3003'
        build: ./accounts
        env_file:
            - ./accounts/.env
        environment:
            - IS_SAAS_SERVICE=true
        depends_on:
            - backend

    dashboard:
        ports:
            - '3000:3000'
        build: ./dashboard
        env_file:
            - ./dashboard/.env
        environment:
            - IS_SAAS_SERVICE=true
        depends_on:
            - backend
            - accounts

    home:
        ports:
            - '1444:1444'
        env_file:
            - ./home/.env
        environment:
            - IS_SAAS_SERVICE=true
        build: ./home

    status-page:
        ports:
            - '3006:3006'
        build: ./status-page
        env_file:
            - ./status-page/.env
        environment:
            - IS_SAAS_SERVICE=true
        depends_on:
            - backend
            - accounts
            - dashboard

    admin-dashboard:
        ports:
            - '3100:3100'
        build: ./admin-dashboard
        env_file:
            - ./admin-dashboard/.env
        environment:
            - IS_SAAS_SERVICE=true
        depends_on:
            - backend
            - accounts

    http-test-server:
        ports:
            - '3010:3010'
        env_file:
            - ./http-test-server/.env
        environment:
            - IS_SAAS_SERVICE=true
        build: ./http-test-server

    licensing:
        ports:
            - '3004:3004'
        env_file:
            - ./licensing/.env
        environment:
            - IS_SAAS_SERVICE=true
        build: ./licensing

    probe1:
        ports:
            - '3024:3024'
        build: ./probe
        env_file:
            - ./probe/.env
        environment:
            - PORT=3024
            - SERVER_URL=http://backend:3002
            - PROBE_NAME=Probe 1
            - PROBE_KEY=test-key
            - IS_SAAS_SERVICE=true
        depends_on:
            - backend

    probe2:
        ports:
            - '3025:3025'
        build: ./probe
        env_file:
            - ./probe/.env
        environment:
            - PORT=3025
            - SERVER_URL=http://backend:3002
            - PROBE_NAME=Probe 2
            - PROBE_KEY=test-key
            - IS_SAAS_SERVICE=true
        depends_on:
            - backend

    api-docs:
        ports:
            - '1445:1445'
        build: ./api-docs
        env_file:
            - ./api-docs/.env
        environment:
            - IS_SAAS_SERVICE=true

    ##IMPORTANT:
    ## This container is an SMTP server used to send emails.
    haraka:
        ports:
            # port 25 is usually blocked or only accessible by root user
            # if access is granted to this port we can use it as default port
            # - '25:25'
            - '2525:2525'
        build:
            context: ./haraka
            args:
                PORT: '2525'
        environment:
            - SMTP_USER="user@hackerbay.io"
            - SMTP_PASSWORD="hackerbay"

volumes:
    mongodata:
