version: '3.7'

services:
    
    haraka:
        extends:
            file: ./docker-compose.base.yml
            service: haraka
    
    redis:
        extends:
            file: ./docker-compose.base.yml
            service: redis

    clickhouse:
        extends:
            file: ./docker-compose.base.yml
            service: clickhouse

    postgres:
        extends:
            file: ./docker-compose.base.yml
            service: postgres
    
    notification:
        extends:
            file: ./docker-compose.base.yml
            service: notification
        
    accounts:
        extends:
            file: ./docker-compose.base.yml
            service: accounts
       

    dashboard:
        extends:
            file: ./docker-compose.base.yml
            service: dashboard
        
    

    status-page:
        extends:
            file: ./docker-compose.base.yml
            service: status-page
            
        

    dashboard-api:
        extends:
            file: ./docker-compose.base.yml
            service: dashboard-api
       


    link-shortner:
        extends:
            file: ./docker-compose.base.yml
            service: link-shortner
        

    workflow:
        extends:
            file: ./docker-compose.base.yml
            service: workflow
        
    
    workers:
        extends:
            file: ./docker-compose.base.yml
            service: workers
        
    

    probe:   
        extends:
            file: ./docker-compose.base.yml
            service: probe
        

    identity:
        extends:
            file: ./docker-compose.base.yml
            service: identity
       
    

    probe-api:
        extends:
            file: ./docker-compose.base.yml
            service: probe-api
       

    file:
       extends:
            file: ./docker-compose.base.yml
            service: file
        

  
    home:
        extends:
            file: ./docker-compose.base.yml
            service: home
        
    
    api-reference:
        extends:
            file: ./docker-compose.base.yml
            service: api-reference


    nginx:
       extends:
            file: ./docker-compose.base.yml
            service: nginx
