version: '3.7'

services:
    
    haraka:
        extends:
            file: ./docker-compose.base.yml
            service: haraka
        build:
            network: host
            context: .
            dockerfile: ./Haraka/Dockerfile

    
    redis:
        extends:
            file: ./docker-compose.base.yml
            service: redis

    clickhouse:
        extends:
            file: ./docker-compose.base.yml
            service: clickhouse

    postgres:
        extends:
            file: ./docker-compose.base.yml
            service: postgres
    
    notification:
        extends:
            file: ./docker-compose.base.yml
            service: notification
        ports:
            - 9111:9229 # Debugging port.
            - 3191:3191
        build:
            network: host
            context: .
            dockerfile: ./Notification/Dockerfile
        
    accounts:
        extends:
            file: ./docker-compose.base.yml
            service: accounts
        build:
            network: host
            context: .
            dockerfile: ./Accounts/Dockerfile
       

    dashboard:
        extends:
            file: ./docker-compose.base.yml
            service: dashboard
        build:
            network: host
            context: .
            dockerfile: ./Dashboard/Dockerfile
        
    

    status-page:
        extends:
            file: ./docker-compose.base.yml
            service: status-page
        build:
            network: host
            context: .
            dockerfile: ./StatusPage/Dockerfile
            
        

    dashboard-api:
        extends:
            file: ./docker-compose.base.yml
            service: dashboard-api
        build:
            network: host
            context: .
            dockerfile: ./DashboardAPI/Dockerfile
       


    link-shortner:
        extends:
            file: ./docker-compose.base.yml
            service: link-shortner
        build:
            network: host
            context: .
            dockerfile: ./LinkShortner/Dockerfile
        

    workflow:
        extends:
            file: ./docker-compose.base.yml
            service: workflow
        build: 
            network: host
            context: .
            dockerfile: ./Workflow/Dockerfile
        
    
    workers:
        extends:
            file: ./docker-compose.base.yml
            service: workers
        
    

    probe:   
        extends:
            file: ./docker-compose.base.yml
            service: probe
        build:
            network: host
            context: .
            dockerfile: ./Probe/Dockerfile
        

    identity:
        extends:
            file: ./docker-compose.base.yml
            service: identity
        build:
            network: host
            context: .
            dockerfile: ./Identity/Dockerfile
       
    

    probe-api:
        extends:
            file: ./docker-compose.base.yml
            service: probe-api
        build:
            network: host
            context: .
            dockerfile: ./ProbeAPI/Dockerfile
       

    file:
       extends:
            file: ./docker-compose.base.yml
            service: file
        

  
    home:
        extends:
            file: ./docker-compose.base.yml
            service: home
        build:
            network: host
            context: .
            dockerfile: ./Home/Dockerfile
        
    
    api-reference:
        extends:
            file: ./docker-compose.base.yml
            service: api-reference
        build:
            network: host
            context: .
            dockerfile: ./ApiReference/Dockerfile


    nginx:
       extends:
            file: ./docker-compose.base.yml
            service: nginx
