version: '3.7'

services:
    
    haraka:
        extends:
            file: ./docker-compose.base.yml
            service: haraka
        build:
            network: host
            context: .
            dockerfile: ./Haraka/Dockerfile

    
    redis:
        extends:
            file: ./docker-compose.base.yml
            service: redis

    clickhouse:
        extends:
            file: ./docker-compose.base.yml
            service: clickhouse

    postgres:
        ports: 
            - '5400:5432'
        extends:
            file: ./docker-compose.base.yml
            service: postgres
    
    notification:
        extends:
            file: ./docker-compose.base.yml
            service: notification
        ports:
            - 9111:9229 # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./Notification/Dockerfile
        
    accounts:
        extends:
            file: ./docker-compose.base.yml
            service: accounts
        build:
            network: host
            context: .
            dockerfile: ./Accounts/Dockerfile
       

    dashboard:
        extends:
            file: ./docker-compose.base.yml
            service: dashboard
        build:
            network: host
            context: .
            dockerfile: ./Dashboard/Dockerfile
        
    

    status-page:
        extends:
            file: ./docker-compose.base.yml
            service: status-page
        build:
            network: host
            context: .
            dockerfile: ./StatusPage/Dockerfile
            
        

    dashboard-api:
        extends:
            file: ./docker-compose.base.yml
            service: dashboard-api
        ports:
            - '9232:9229' # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./DashboardAPI/Dockerfile
       


    link-shortner:
        extends:
            file: ./docker-compose.base.yml
            service: link-shortner
        ports:
            - '9826:9229' # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./LinkShortner/Dockerfile
        

    workflow:
        extends:
            file: ./docker-compose.base.yml
            service: workflow
        ports:
          - '9212:9229' # Debugging port.
        build: 
            network: host
            context: .
            dockerfile: ./Workflow/Dockerfile
        
    
    workers:
        ports:
          - '9654:9229' # Debugging port.
        extends:
            file: ./docker-compose.base.yml
            service: workers
        
    

    probe-1:   
        extends:
            file: ./docker-compose.base.yml
            service: probe-1
        ports:
          - '9655:9229' # Debugging port.
        build:
            network: host
            context: .
            dockerfile: ./Probe/Dockerfile
        

    identity:
        ports:
          - '9132:9229' # Debugging port.
        extends:
            file: ./docker-compose.base.yml
            service: identity
        build:
            network: host
            context: .
            dockerfile: ./Identity/Dockerfile
       
    

    probe-api:
        ports:
          - '9932:9229' # Debugging port.
        extends:
            file: ./docker-compose.base.yml
            service: probe-api
        build:
            network: host
            context: .
            dockerfile: ./ProbeAPI/Dockerfile
       

    file:
        ports:
          - '9012:9229' # Debugging port.
        extends:
            file: ./docker-compose.base.yml
            service: file
        

  
    home:
        ports:
          - '9235:9229' # Debugging port.
        extends:
            file: ./docker-compose.base.yml
            service: home
        build:
            network: host
            context: .
            dockerfile: ./Home/Dockerfile
        
    
    api-reference:
        ports:
          - '9178:9229' # Debugging port.
        extends:
            file: ./docker-compose.base.yml
            service: api-reference
        build:
            network: host
            context: .
            dockerfile: ./ApiReference/Dockerfile


    nginx:
       extends:
            file: ./docker-compose.base.yml
            service: nginx

volumes:
    postgres:
    clickhouse:

networks:
  oneuptime: 
    driver: bridge