sudo: required

services:
  - docker

env:
  global:
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

language: node_js

node_js:
  - '6'

before_install:
  - sudo apt-get update
  - sudo apt-get install curl libc6 libcurl3 zlib1g bash git python openssl
  - curl -sSL https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc;
  - gcloud components update kubectl;

install:
  - npm install

after_success:
# Build Docker Image
  - docker build -t fyipeproject/api-docs:1.0.$TRAVIS_BUILD_NUMBER .

deploy:
  - provider: script
    script: bash scripts/production.sh production
    on:
      branch: release
  - provider: script
    script: bash scripts/staging.sh staging
    on:
      branch: master
  
#Notify Team on Slack
notifications:
   slack: hackerbaycompany:EuerXOxxChZKW2ITachshgKL