
# Please change this to the domain name / IP where OneUtpime server is hosted on. 
host: localhost

# You can safely ignore values below this line. 
# ------------------------------------------------

replicaCount: 1

image:
  registry: docker.io
  repository: oneuptime
  pullPolicy: Always
  tag: release

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


nodeEnvironment: production

billing: 
  enabled: false
  publicKey: 
  privateKey: 
  smsDefaultValueInCents: 
  callDefaultValueInCentsPerMinute: 

disableAutomaticIncidentsCreation: 

subscriptionPlan: 
  basic: 
  growth: 
  scale: 
  enterprise: 

meteredPlan: 
  activeMonitoring: 

analytics: 
  host:
  key: 


incidents:
  disableAutomaticCreation: 

statusPage: 
  cnameRecord: 

secrets: 
  oneuptime: please-change-this
  encryption: please-change-this

clickhouse: 
  user: 
  pasword: 
  database: 
  host: 
  port: 

postgres: 
  port: 
  host: 
  username: 
  password: 
  database: 

  # Advanced and optional options. 
  sslCa: 
  sslKey: 
  sslCert: 
  sslRejectUnauthorized: 

redis: 
  username: 
  password: 
  host: 
  port:
  database: 

  # Advanced and optional options. 
  tlsCa: 
  tlsSentinelMode: 

port: 
  home: 1444
  dashboardApi: 3002
  apiDocs: 1445
  workflow: 3099
  linkShortener: 3521
  alert: 3088
  probeApi: 3400
  probe: 3500
  testServer: 3800
  file: 3125
  identity: 3087
  notificaiton: 3191
  realtime: 3300
  workers: 3452
  accounts: 3003
  statusPage: 3105
  dashboard: 3009
  adminDashboard: 3158
