apiVersion: v1
kind: Service
metadata:
    name: mongo-headless
    labels:
        name: mongo-headless
spec:
    ports:
        - port: 27017
          targetPort: 27017
    clusterIP: None
    selector:
        role: mongo

---
# stateful set config for mongo
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongo
spec:
    serviceName: mongo-headless
    replicas: 3
    selector:
        matchLabels:
            role: mongo
    template:
        metadata:
            labels:
                role: mongo
                environment: production
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                - name: mongo
                  image: mongo:4.2.3
                  command: ['/bin/sh', '-c']
                  args:
                      [
                          'echo 2J2W5Jm7G38y169r8s5T1dW > mongo.key; chmod 600 mongo.key; mongod --replSet fyipe --noauth --smallfiles --noprealloc --bind_ip_all',
                      ]
                  ports:
                      - containerPort: 27017
---

