##################################################################################  
## Important: If you're implenting this in the enterprise environment, this should always be `false`. 
## Is this Fyipe SaaS service. This will deploy all the SaaS env vars

saas: 
  isSaasService: false

###################################################################################
fyipe:
  tls:
    enabled: 
    crt: 
    key:  
    host: 
  emailEnabled: true
  callEnabled: true
  smsEnabled: true
  clusterKey: test-cluster-key
  twilio:
    accountSid: 
    authToken:
    phoneNumber: 
    verificationSid: 
    twilioAlertLimit: 99999
  smtpMail: 
    email: 
    password: 
    fromName: Fyipe
    smtpServer: 
    smtpPort: 
    smtpSecure: 

host: 
  backendPort: 3002
  homePort: 1444
  slackPort: 1267
  licensingPort: 3004
  statusPagePort: 3006
  dashboardPort: 3000
  accountsPort: 3003
  apiDocsPort: 1445
  adminDashboardPort: 3100
  backendServicePort: 80
  homeServicePort: 80
  apiDocsServicePort: 80
  slackServicePort: 80
  statusPageServicePort: 80
  dashboardServicePort: 80
  accountsServicePort: 80
  adminDashboardServicePort: 80
  backendNodePort: 80
  statusPageNodePort: 80
  dashboardNodePort: 80
  accountsNodePort: 80
  adminDashboardNodePort: 80
  licensingServicePort: 80


probes:
  probe1: 
    port: 3024
    name: Probe 1
    key: test-key
    servicePort: 80
  probe2: 
    name: Probe 2
    port: 3025
    key: test-key
    servicePort: 80

rateLimitter:
  enabled: false
  requestLimit: 5000
  requestLimitTimePeriodInMS: 216000

encryption:
  secret: 'sample-secret'

## Fyipe official image version on Docker Hub
## ref: https://hub.docker.com/u/fyipeproject
##
image:
  registry: docker.io
  repository: fyipeproject
  tag: test
  pullPolicy: Always
  restartPolicy: Always

replicaCount: 1

## Service Configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer or ClusterIP
##
service:
  type: ClusterIP

##################################################################################
## IMPORTANT: 
## Values for Subcharts
##

redis: 
  redisPort: 6379
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: latest
    pullPolicy: Always
  usePassword: false
  persistence:
    enabled: true
    mountPath: /bitnami/mongodb
    size: 20Gi


mongodb: 
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: latest
    pullPolicy: Always
  mongodbRootPassword: root
  mongodbUsername: fyipe
  mongodbPassword: password
  mongodbDatabase: fyipedb
  replicaSet:
    enabled: true
    name: rs0
    useHostnames: true
    key: mongodbfyipe
    secondary: 1
    arbiter: 1
  persistence:
    enabled: true
    mountPath: /bitnami/mongodb
    size: 20Gi
  useStatefulSet: true

  ##################################################################################