########-INIT-SCRIPT-##########
apiVersion: batch/v1
kind: Job
metadata:
    name: init-script
spec:
    template:
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository "init-script" .Values.image.tag }}
                  name: init-script
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  env:
                      - name: MONGO_URL
                        value:  {{ template "fyipe.mongodbConnectionString" . }}
                      - name: NODE_ENV
                        value: 'production'
            restartPolicy: Never
---
####################################