########-PROBE-#################
#Probe service and deployement
{{- range $key, $value := $.Values.probes }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ printf "%s-%s" $.Release.Name $key  }}
    labels:
        app: {{ printf "%s-%s" $.Release.Name $key  }}
spec:
    selector:
        matchLabels:
            app: {{ printf "%s-%s" $.Release.Name $key  }}
    replicas: 1 # THIS SHOULD STRICTLY BE 1
    template:
        metadata:
            labels:
                app: {{ printf "%s-%s" $.Release.Name $key  }}
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" $.Values.image.registry $.Values.image.repository "probe" $.Values.image.tag }}
                  name: {{ printf "%s-%s" $.Release.Name $key  }}
                  imagePullPolicy: {{ $.Values.image.pullPolicy }}
                  env:
                      - name: SERVER_URL
                        value: {{ template "fyipe.serverUrl" $ }}
                      - name: PORT
                        value: {{ $value.port | quote }}
                      - name: PROBE_NAME
                        value: {{ $value.name }}
                      - name: PROBE_KEY
                        value: {{ $value.key }}
                      - name: CLUSTER_KEY
                        value: {{ template "fyipe.clusterKey" . }}
                      {{- if $.Values.saas.isSaasService }}
                      - name: IS_SAAS_SERVICE
                        value: 'true'
                      {{- end }}
                  ports:
                      - containerPort: {{ $value.port }}
                        hostPort: {{ $value.port }}
                        name: {{ printf "%s-%s" $.Release.Name $key  }}
            restartPolicy: {{ $.Values.image.restartPolicy }}

---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ printf "%s-%s" $.Release.Name $key  }}
    name: {{ printf "%s-%s" $.Release.Name $key  }}
spec:
    ports:
        - port: {{ $value.servicePort }}
          targetPort: {{ $value.port }}
    selector:
        app: {{ printf "%s-%s" $.Release.Name $key }}
    type: {{ $.Values.service.type }}
---
###########################
{{- end }}