########-PROBE-#################
#Probe service and deployement
{{- range $key, $value := $.Values.probes }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ printf "%s-%s" $.Release.Name $key  }}
    namespace: {{ $.Release.Namespace }}
    labels:
        app: {{ printf "%s-%s" $.Release.Name $key  }}
        app.kubernetes.io/part-of: fyipe
        app.kubernetes.io/managed-by: Helm
spec:
    selector:
        matchLabels:
            app: {{ printf "%s-%s" $.Release.Name $key  }}
    replicas: 1 # THIS SHOULD STRICTLY BE 1
    template:
        metadata:
            labels:
                app: {{ printf "%s-%s" $.Release.Name $key  }}
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" $.Values.image.registry $.Values.image.repository "probe" $.Values.image.tag }}
                  name: {{ printf "%s-%s" $.Release.Name $key  }}
                  imagePullPolicy: {{ $.Values.image.pullPolicy }}
                  resources:
                    requests:
                      cpu: 250m
                    limits:
                      cpu: 500m
                  env:
                      - name: SERVER_URL
                        value: {{ template "fyipe.serverUrl" $ }}
                      - name: DATA_INGESTOR_URL
                        value: {{ template "fyipe.dataIngestorUrl" $ }}
                      - name: PORT
                        value: {{ $value.port | quote }}
                      - name: PROBE_NAME
                        value: {{ $value.name }}
                      - name: PROBE_KEY
                        value: {{ $value.key }}
                      {{- if $.Values.newRelic.probe.licenseKey }}
                      - name: NEW_RELIC_LICENSE_KEY
                        value: {{ $.Values.newRelic.probe.licenseKey }}
                      {{- end }}
                      {{- if $.Values.newRelic.probe.appName }}
                      - name: NEW_RELIC_APPLICATION_NAME
                        value: {{ $.Values.newRelic.probe.appName}}
                      {{- end }}
                      - name: CLUSTER_KEY
                        valueFrom:
                          configMapKeyRef:
                            name: {{ printf "%s-%s" $.Release.Name "configmap"  }}
                            key: clusterkey
                      {{- if $.Values.saas.isSaasService }}
                      - name: IS_SAAS_SERVICE
                        value: 'true'
                      - name: SLACK_ERROR_LOG_WEBHOOK
                        value: {{ $.Values.saas.slackErrorLog.webhook }}
                      - name: SLACK_ERROR_LOG_CHANNEL
                        value: {{ $.Values.saas.slackErrorLog.channel }}
                      {{- end }}
                      - name: NODE_ENV
                        value: {{ $.Values.nodeEnv }}
                      - name: SENTRY_DSN
                        value: {{ $.Values.sentry.probe.dsn }}
                  ports:
                      - containerPort: {{ $value.port }}
                        hostPort: {{ $value.port }}
                        name: {{ printf "%s-%s" $.Release.Name $key  }}
            restartPolicy: {{ $.Values.image.restartPolicy }}

---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ printf "%s-%s" $.Release.Name $key  }}
        app.kubernetes.io/part-of: fyipe
        app.kubernetes.io/managed-by: Helm
    name: {{ printf "%s-%s" $.Release.Name $key  }}
    namespace: {{ $.Release.Namespace }}
spec:
    ports:
        - port: {{ $value.servicePort }}
          targetPort: {{ $value.port }}
    selector:
        app: {{ printf "%s-%s" $.Release.Name $key }}
    type: ClusterIP
---
###########################
{{- end }}