############----STATUS-PAGE-INGRESS--#####################################
{{- if .Values.fyipe.hosts.host1.host }} 
{{- range $key, $value := $.Values.statusPage.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
  name: {{ printf "%s-%s-%s" $.Release.Name $key "statuspage"  }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: fyipe
    app.kubernetes.io/managed-by: Helm
spec:
  {{- if  $value.tls.enabled }} 
  tls:
    - hosts:
      - {{  $value.host }} 
      secretName: {{ printf "%s-%s-%s" $.Release.Name $key "statuspagetls"  }}
  {{- end }}
  rules:
    {{- if  $value.host }} 
    - host: {{  $value.host }} 
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-%s" $.Release.Name "status"  }}
                port:
                  number: 80
---
{{- end }}
{{- end }}
##################################