###########-----STATUS PAGE------#################
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ printf "%s-%s" .Release.Name "status"  }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ printf "%s-%s" .Release.Name "status"  }}
        app.kubernetes.io/part-of: fyipe
        app.kubernetes.io/managed-by: Helm
spec:
    selector:
        matchLabels:
            app: {{ printf "%s-%s" .Release.Name "status"  }}
    replicas: {{ .Values.replicaCount }}
    template:
        metadata:
            labels:
                app: {{ printf "%s-%s" .Release.Name "status"  }}
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository "status-page" .Values.image.tag }}
                  name: {{ printf "%s-%s" .Release.Name "status"  }}
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  env:
                    - name: FYIPE_HOST
                      value: {{ .Values.fyipe.hosts.host1.host }}
                    - name: NODE_ENV
                      value: 'production'
                    {{- if .Values.saas.isSaasService }}
                    - name: IS_SAAS_SERVICE
                      value: 'true'
                    - name: STATUSPAGE_CERT
                      value: {{ .Values.statusPage.cert }}
                    - name: STATUSPAGE_PRIVATEKEY
                      value: {{ .Values.statusPage.key }}
                    {{- end }}
                    {{- if .Values.backendProtocol }}
                    - name: BACKEND_PROTOCOL
                      value: {{ .Values.backendProtocol }}
                    {{- end }}
                  ports:
                      - containerPort: {{ .Values.host.statusPageHttpPort }}
                        hostPort: {{ .Values.host.statusPageHttpPort }}
                        name: {{ printf "%s-%s" .Release.Name "status"  }}
                      - containerPort: {{ .Values.host.statusPageHttpsPort }}
                        hostPort: {{ .Values.host.statusPageHttpsPort }}
                        name: {{ printf "%s-%s" .Release.Name "status"  }}
            restartPolicy: {{ .Values.image.restartPolicy }}
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ printf "%s-%s" .Release.Name "status"  }}
        app.kubernetes.io/part-of: fyipe
        app.kubernetes.io/managed-by: Helm
    name: {{ printf "%s-%s" .Release.Name "status"  }}
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - port: {{ .Values.host.statusPageHttpServicePort }}
          targetPort: {{ .Values.host.statusPageHttpPort }}
        - port: {{ .Values.host.statusPageHttpsServicePort }}
          targetPort: {{ .Values.host.statusPageHttpsPort }}
    selector:
        app: {{ printf "%s-%s" .Release.Name "status"  }}
    {{- if .Values.saas.isSaasService }}
    # Load balancer becasue we need to expose Status page on different domains. 
    type: LoadBalancer
    {{- else}}
    type: ClusterIP
    {{- end }}
---
########################################