##################################################################################  
## Important: If you're implenting this in the enterprise environment, this should always be `false`. 
## Is this Fyipe SaaS service. This will deploy all the SaaS env vars

##


saas: 
    isSaasService: true
    stripe: 
      publicKey: pk_test_UynUDrFmbBmFVgJXd9EZCvBj00QAVpdwPv
      privateKey: sk_test_YxwnzywggtAd8jDaHecNmHiN
    airtable: 
      key: keyenXfDDP4Dutazt
      baseId: appgek0ngJaHhppeJ
    amplitude: 
      key: 4b76c47248f969446af69dfdbf687d90
    licensing:
      airtable: 
        key: key9VuqGqj1Pp07Q8
        baseId: appksCeuKfCS0e8fR
      tokenSecret: LicenseTokenSecret
    support: 
      slackToken: xoxp-369430749728-370026359715-370129302482-08f43c6a1306d2e8f4be4b0d8abbdb80


fyipe:
  hosts:
    host1: 
      host: test.fyipe.com
      tls:
        enabled: false
        crt: 
        key: 
    host2:
      host: staging.fyipe.com
      tls:
        enabled: false
        crt: 
        key: 
  licensingUrl: https://fyipe.com/license

image:
  registry: docker.io
  repository: fyipeproject
  tag: test
  pullPolicy: Always
  restartPolicy: Always

replicaCount: 1