##################################################################################
## Important: If you're implenting this in the enterprise environment, this should always be `false`.
## Is this Fyipe SaaS service. This will deploy all the SaaS env vars

##

saas:
    isSaasService: true
    slackErrorLog:
        webhook: https://hooks.slack.com/services/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
        channel: fyipe-logs 
    stripe:
        publicKey: pk_test_UynUDrFmbBmFVgJXd9EZCvBj00QAVpdwPv
        privateKey: sk_test_YxwnzywggtAd8jDaHecNmHiN
    airtable:
        key: keye3gzJRafDIhRKg
        baseId: appgek0ngJaHhppeJ
    amplitude:
        key: 4b76c47248f969446af69dfdbf687d90
    licensing:
        airtable:
            key: keye3gzJRafDIhRKg
            baseId: appksCeuKfCS0e8fR
        tokenSecret: LicenseTokenSecret

fyipe:
    hosts:
        host1:
            host: localhost
            tls:
                enabled: false
                crt:
                key:
    licensingUrl: http://localhost/license

image:
    registry: docker.io
    repository: fyipeproject
    tag: test
    pullPolicy: Always
    restartPolicy: Always

nginx-ingress-controller:
    service:
        type: NodePort
    hostNetwork: true

isTesting: true
