##################################################################################
## Important: If you're implenting this in the enterprise environment, this should always be `false`.
## Is this Fyipe SaaS service. This will deploy all the SaaS env vars

##

saas:
    isSaasService: true
    slackErrorLog:
        webhook: https://hooks.slack.com/services/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
        channel: fyipe-logs
    stripe:
        publicKey: pk_test_UynUDrFmbBmFVgJXd9EZCvBj00QAVpdwPv
        privateKey: sk_test_YxwnzywggtAd8jDaHecNmHiN
    airtable:
        key: keye3gzJRafDIhRKg
        baseId: appgek0ngJaHhppeJ
    amplitude:
        key: 4b76c47248f969446af69dfdbf687d90
    licensing:
        airtable:
            key: keye3gzJRafDIhRKg
            baseId: appksCeuKfCS0e8fR
        tokenSecret: LicenseTokenSecret

httpTestServer:
    hosts:
        host1:
            host: staging-test-server.fyipe.com
            tls:
                enabled: false
                crt:
                key:
fyipe:
    hosts:
        host1:
            host: staging.fyipe.com
            tls:
                enabled: false
                crt:
                key:
    licensingUrl: https://fyipe.com/license

image:
    registry: docker.io
    repository: fyipeproject
    tag: master
    pullPolicy: Always
    restartPolicy: Always

replicaCount: 1

# This should be 32 chars in length.
encryptionKey: pg#K^C$-)IGOg6DYXDGq2jdmfws0MiR7

# Is backend on HTTPS?
backendProtocol: 'https'

haraka:
    domain: 'fyipe.com'
    user: 'noreply@fyipe.com'
    password: 'tX8z_bDEcRdRHnyKxAHYEQk_B'
