applicationApiVersion: v1beta1

# IMPORTANT: These IDs must match your listing ID in Marketplace.
x-google-marketplace:
  partnerId: fyipe-public
  solutionId: fyipe

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageUbbagent:
    type: string
<<<<<<< HEAD
    default: gcr.io/cloud-marketplace-tools/metering/ubbagent
=======
    default: gcr.io/ubbagent:latest
>>>>>>> 5a3307b09e7c8d9f5ea924725906f968bb6db339
    x-google-marketplace:
      type: IMAGE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

required:
- name
- namespace