name: OneUptime ACME HTTP Audit

on:
  push:
    branches: 
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - name: Run audit
        run: |-
          cd oneuptime-acme-http-01
          npm ci
          npm run audit

