name: Accounts Staging Deploy

on:
  push:
    branches: 
      - "staging-release"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh
      - run: chmod +x ./ci/scripts/deployment-setup.sh
      - run: bash ./ci/scripts/deployment-setup.sh
      - run: chmod +x ./ci/scripts/deployment-staging-setup.sh
      - run: bash ./ci/scripts/deployment-staging-setup.sh
      - run: sudo docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        # Build and deploy accounts.
      - run: sudo docker login --username ${{secrets.DOCKERHUBUSERNAME}} --password ${{secrets.DOCKERHUBPASSWORD}}
      - run: sudo docker buildx create --use
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/accounts:4.0.${{github.run_number}} --push ./accounts
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/accounts:master --push ./accounts
      - run: sudo kubectl set image deployment/fi-accounts fi-accounts=oneuptime/accounts:4.0.${{github.run_number}}
        # Cleanup
      - run: chmod +x ./ci/scripts/deployment-cleanup.sh
      - run: ./ci/scripts/deployment-cleanup.sh

