name: Account Jobs

on:
  push:
    # run this workflow when changes are pushed to accounts
    paths:
      - "accounts/**"
      - ".github/workflows/accounts.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run tests
        run: |-
          sudo apt-get update
          cd accounts
          npm ci
          npm run audit
          npm run dep-check

