name: Nginx Production Deploy

on:
  push:
    branches:
      - release
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      CI_PIPELINE_ID: ${{github.run_number}}
     
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh
      - run: sudo docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        # Build and deploy LighthouseRunner.
      - run: sudo docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      - run: sudo docker buildx create --use
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/nginx:5.0.$CI_PIPELINE_ID --push -f ./nginx/Dockerfile ./nginx
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/nginx:latest --push -f ./nginx/Dockerfile ./nginx
