name: Haraka Production Deploy

on:
  push:
    branches:
      - release
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      CI_PIPELINE_ID: ${{github.run_number}}
     
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh

      - run: sudo docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        # Build and deploy fi-haraka.
      - run: sudo docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      - run: sudo docker buildx create --use
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/haraka:5.0.$CI_PIPELINE_ID --push -f ./haraka/Dockerfile ./haraka
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/haraka:latest --push -f ./haraka/Dockerfile ./haraka
      - run: chmod +x ./ci/scripts/deployment-setup.sh
      - run: bash ./ci/scripts/deployment-setup.sh
      - run: chmod +x ./ci/scripts/deployment-production-setup.sh
      - run: bash ./ci/scripts/deployment-production-setup.sh
      - run: kubectl set image deployment/fi-haraka fi-haraka=oneuptime/haraka:5.0.$CI_PIPELINE_ID
        # Cleanup
      - run: chmod +x ./ci/scripts/deployment-cleanup.sh
      - run: ./ci/scripts/deployment-cleanup.sh
