name: API Docs Docker Build
on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   
      - 'release'

jobs:
 # define jobs to build docker imag
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Preinstall 
        uses: npm run preinstall
        
      # build image for home
      - name: build docker image
        run: sudo docker build -f ./ApiDocs/Dockerfile .
