name: Licensing Docker Build

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   
      - 'release'

jobs:
 # define job to build docker image
  docker-build:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Preinstall 
        run: npm run prerun

      # build image for licensing
      - name: build docker image
        run: sudo docker build -f ./Licensing/Dockerfile .