name: Alert Docker Build

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   
      - 'release'

jobs:
 # define job to build docker image
   docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Preinstall 
        uses: npm run preinstall

      # build image for mail service
      - name: build docker image
        run: sudo docker build -f ./Alert/Dockerfile .