name: Integration Docker Build

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   
      - 'release'

jobs:
 # define job to build docker image
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Preinstall 
        run: npm run prerun
        
      # build image for licensing
      - name: build docker image
        run: sudo docker build -f ./Integration/Dockerfile .