name: Helm Chart Production Image Deploy to DockerHub

on:
  push:
    branches:
      - "release"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
     
      - run: npm run prerun
      - run: sudo docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        # Build and deploy accounts.
      - run: sudo docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      - run: sudo docker buildx create --use
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/helm-chart:5.0.$CI_PIPELINE_ID --push -f ./HelmChart/Dockerfile .
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/helm-chart:release --push -f ./HelmChart/Dockerfile .
      
