name: Status Page Test Image Deploy to DockerHub

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUBPASSWORD: ${{secrets.DOCKERHUBPASSWORD}}
      DOCKERHUBUSERNAME: ${{secrets.DOCKERHUBUSERNAME}}
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
     
      - run: sudo docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        # Build and deploy status-page.
      - run: sudo docker login --username $DOCKERHUBUSERNAME --password $DOCKERHUBPASSWORD
      - run: sudo docker buildx create --use
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/status-page:5.0.$CI_PIPELINE_ID-test --push -f ./StatusPage/Dockerfile .
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/status-page:test --push -f ./StatusPage/Dockerfile .
      
