name: JavaScript SDK Production Deploy

on:
  push:
    branches: 
      - "release"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: chmod +x ../ci/scripts/version-setup.sh
      - run: ../ci/scripts/version-setup.sh
      - run: json -I -f package.json -e 'this.name="oneuptime"'
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run: npm run build
      - run: npm publish
