name: Lighthouse Runner Production Deploy

on:
  push:
    branches: 
      - "release"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh
      - run: chmod +x ./ci/scripts/deployment-setup.sh
      - run: bash ./ci/scripts/deployment-setup.sh
      - run: chmod +x ./ci/scripts/deployment-production-setup.sh
      - run: bash ./ci/scripts/deployment-production-setup.sh
      - run: sudo docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        # Build and deploy lighthouse-runner.
      - run: sudo docker login --username $DOCKERHUBUSERNAME --password $DOCKERHUBPASSWORD
      - run: sudo docker buildx create --use
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/lighthouse-runner:3.0.$CI_PIPELINE_IID --push ./lighthouse-runner
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/lighthouse-runner:master --push ./lighthouse-runner
      - run: sudo kubectl set image deployment/fi-lighthouse fi-lighthouse=oneuptime/lighthouse-runner:3.0.$CI_PIPELINE_IID
        # Cleanup
      - run: chmod +x ./ci/scripts/deployment-cleanup.sh
      - run: ./ci/scripts/deployment-cleanup.sh
