name: Main

on: 
  push:
    branches-ignore:
      - 'hotfix-*'   # excludes hotfix branches

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: ./.github/workflows/data-ingestor/audit.yaml
