name: OneUptime GL Manager Audit

on:
  push:
    branches: [master]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - name: Run audit
        run: |-
          cd oneuptime-gl-manager
          npm ci
          npm run audit

