name: OneUptime ACME HTTP Production Deploy

on:
  push:
    branches: 
      - "staging-release"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: sudo npm install -g json
      - run: cd oneuptime-acme-http-01
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh
      - run: json -I -f package.json -e 'this.name="oneuptime-acme-http-01-staging"'
      - run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc
      - run: npm publish
      - run: cd ..
      - run: chmod +x ./ci/scripts/cleanup.sh
      - run: ./ci/scripts/cleanup.sh
