name: OneUptime LetsEncrypt Store Production Deploy

on:
  push:
    branches: 
      - "release"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: sudo npm install -g json
      - run: cd oneuptime-gl-manager
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh
      - run: json -I -f package.json -e 'this.name="oneuptime-gl-manager"'
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run: npm publish
      - run: cd ..
      - run: chmod +x ./ci/scripts/cleanup.sh
      - run: ./ci/scripts/cleanup.sh
