
name: Helm Chart Release
on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   # excludes hotfix branches
      - 'release'

jobs:
  helm-chart-docker-image-deploy:
    runs-on: ubuntu-latest
    env: 
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        CI_COMMIT_AUTHOR: Continuous Integration
    steps:

      - name: Clone Repo  
        run: |
          git clone git@github.com:OneUptime/helm-chart.git

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install Helm 
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
         
      - name: Build and Package Helm chart
        run: |
          cd HelmChart/public
          helm lint oneuptime
          helm package oneuptime --version 7.0.1 --app-version 7.0.1 
          cd .. 
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.HELM_CHART_GITHUB_REPO_DEPLOY_KEY }}'
          
          cp -r ./public/* ./helm-chart
          cd helm-chart
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "hello@oneuptime.com"
          helm repo index .
          git add -A
          git commit -m "Helm Chart Release 7.0.1"
          git push origin master

